services:
  nginx:
    build: ./srcs/requirements/nginx
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html  
  mariadb:
    build: ./srcs/requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mariadb_data:/var/lib/mysql 
  wordpress:
    build: ./srcs/requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
volumes:
  wordpress_data:
  mariadb_data:
