#     listen 443 ssl;
#  listen [::]:443 ssl;    

# main context
#  ├── events {}  
#  └── http {}  
#       └── server {}    

events {}

http {

    server {
        listen 80;
        listen [::]:80;

        server_name localhost;

        root /var/www/html;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$args;
    }
        
        location ~ \.php$ {  # If the request is for a PHP file, send it to wordpress and pass it to the FastCGI server
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;

            include fastcgi_params;
        }
    }
}
